---
title: Pioneervirt.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
baseurl: ''
url: http://example.com
theme:
  title: Type Theme
  avatar: avatar.png
  gravatar: 
  description: A website with blog posts and pages
  header_text: |
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    <p>Remove all header text in <code>_config.yml</code> to disable this feature.</p>
  header_text_feature_image: 
  footer_text: |
    Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>
  rss: false
  email_address: 
  behance: 
  bitbucket: 
  dribbble: 
  facebook: 
  flickr: 
  github: rohanchandra/type-theme
  google_plus: 
  instagram: 
  linkedin: 
  pinterest: 
  reddit: 
  soundcloud: 
  stack_exchange: 
  steam: 
  tumblr: 
  twitter: twitter
  wordpress: 
  youtube: 
  google_analytics: 
  disqus_shortname: 
  katex: true
  str_follow_on: Follow on
  str_rss_follow: Follow RSS feed
  str_email: Email
  str_next: Next
  str_prev: Prev
  str_continue_reading: Continue reading
  google_fonts: Source+Sans+Pro:400,700,700italic,400italic
  post_navigation: false
paginate: 5
paginate_path: blog/page:num
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
gems:
- jekyll-paginate
